name: DAST Analysis with Syhunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: windows-latest  

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixar Syhunt
        run: |
          Invoke-WebRequest -Uri "https://syhunt.fra1.cdn.digitaloceanspaces.com/community/syhunt-community-7.0.10.3.exe" -OutFile syhunt-installer.exe

      - name: Instalar Syhunt
        run: |
          Start-Process -FilePath syhunt-installer.exe -ArgumentList "/S" -NoNewWindow -Wait

      - name: Executar Análise DAST
        run: |
          "C:\Program Files\Syhunt\SyhuntHybrid.exe" scan -u "https://seu-site-alvo.com" --dast --output report.html

      - name: Upload do Relatório
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: report.html
