name: DAST Analysis with Syhunt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast_scan:
    runs-on: [self-hosted, Windows, X64]  

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
          
      - name: Executar Análise DAST
        run: |
          & "C:\Program Files\Syhunt\SyhuntHybrid.exe" scan -u "https://github.com/Le0-W-L/EcoMolk.git" --dast --output report.html

      - name: Upload do Relatório
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: report.html
